apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: d7ae5398cf8e0ff41fd1db705d68bfb4f3ddfa5c
  description: ""
  annotations:
    pkg/source: backstage-microsite
    pkg/version: 0.0.0
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 19aa7372b3a9337e9ce2d2c881b03f17d39ed9e4
  description: ""
  annotations:
    pkg/base_image: ""
    pkg/browse_url: https://app.snyk.io/org/pkman92/project/f68c77d9-5849-4b01-b8e3-99097f5a212b
    pkg/image_tag: 0.0.0
    pkg/repo: pkman92/backstage
    pkg/source: microsite/package.json
    pkg/vulnerabilities: '{"low":0,"medium":0,"high":0,"critical":0}'
spec:
  type: service
  lifecycle: experimental
  system: domain-1
  owner: yarn
  dependsOn:
  - Component:default/d7ae5398cf8e0ff41fd1db705d68bfb4f3ddfa5c
