apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 809462d8cb5d7b33108c7c2bac3a0d630c3cc9e3
  description: ""
  annotations:
    pkg/source: ubuntu
    pkg/version: xenial
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 308ff95d1c9ce24aaf07363a06f0cc3d071b6af3
  description: ""
  annotations:
    pkg/source: acl/libacl1
    pkg/version: 2.2.52-3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 7f6365b20b953da660b0e4a8d5306a9a828a0c7a
  description: ""
  annotations:
    pkg/source: adduser
    pkg/version: 3.113+nmu3ubuntu4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 5f352b8079e455f15849454ea39b2e6d889e1479
  description: ""
  annotations:
    pkg/source: apparmor/libapparmor1
    pkg/version: 2.10.95-0ubuntu2.11
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 15f84e5f478605045590e85dc63b689b9f5e0af0
  description: ""
  annotations:
    pkg/source: apt
    pkg/version: 1.2.35
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9e4a5d1440c9b75b8d6b841dc003022a61d0566d
  description: ""
  annotations:
    pkg/source: apt/libapt-pkg5.0
    pkg/version: 1.2.35
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 226f70b09bc1ec4eb9554c3c28fd9fb6a85c659c
  description: ""
  annotations:
    pkg/source: attr/libattr1
    pkg/version: 1:2.4.47-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 383949a0fbcad08a01f22964a29473316e0df7b7
  description: ""
  annotations:
    pkg/source: audit/libaudit-common
    pkg/version: 1:2.4.5-1ubuntu2.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 2ed6919b09992a03f1ef084e9cf4209e8439b6d1
  description: ""
  annotations:
    pkg/source: audit/libaudit1
    pkg/version: 1:2.4.5-1ubuntu2.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 667beefbcc6515e67a2fac41446077b9929b0b0e
  description: ""
  annotations:
    pkg/source: base-files
    pkg/version: 9.4ubuntu4.13
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 49ee0e15427d89b5b4ce4de82a5e18edf765681a
  description: ""
  annotations:
    pkg/source: base-passwd
    pkg/version: 3.5.39
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 87f38c10e11c7a57a36115ea0ffd1c38f3e911dd
  description: ""
  annotations:
    pkg/source: bash
    pkg/version: 4.3-14ubuntu1.4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9255304e7dccf0e2d1cbbf01b772cfba30bab192
  description: ""
  annotations:
    pkg/source: bzip2/libbz2-1.0
    pkg/version: 1.0.6-8ubuntu0.2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 78363161b5a11cc53f55d02ebe3aaeccfbc97cb3
  description: ""
  annotations:
    pkg/source: cdebconf/libdebconfclient0
    pkg/version: 0.198ubuntu1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 7e07b7c9dad078ff9741691547ca516899f50559
  description: ""
  annotations:
    pkg/source: coreutils
    pkg/version: 8.25-2ubuntu3~16.04
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dd8bc6a839375048f3b980610dca85c5e7d18635
  description: ""
  annotations:
    pkg/source: cryptsetup/libcryptsetup4
    pkg/version: 2:1.6.6-5ubuntu2.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a471687768f7f2023e4db381d7e28e3955a5d85f
  description: ""
  annotations:
    pkg/source: dash
    pkg/version: 0.5.8-2.1ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8a106462b7ddc3a7a1143c929648406214d3a1f2
  description: ""
  annotations:
    pkg/source: db5.3/libdb5.3
    pkg/version: 5.3.28-11ubuntu0.2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bbd43afdaa0a583f020e1db0081883c1ab8b4642
  description: ""
  annotations:
    pkg/source: debconf
    pkg/version: 1.5.58ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a67752bbab3c985170234fa03216c843e719ff56
  description: ""
  annotations:
    pkg/source: debianutils
    pkg/version: "4.7"
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dc134b884e2ae5efb03d5f0be24eb7c3998067d5
  description: ""
  annotations:
    pkg/source: diffutils
    pkg/version: 1:3.3-3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 02e99874c6833a885ba0b5523acacef29b3d2ddb
  description: ""
  annotations:
    pkg/source: dpkg
    pkg/version: 1.18.4ubuntu1.7
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 79295311f9ae2a1be7b43fd8dbb5b1ca5cd33e37
  description: ""
  annotations:
    pkg/source: e2fsprogs
    pkg/version: 1.42.13-1ubuntu1.2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 33ed539c7a77c708640ab918a0320805d1b32206
  description: ""
  annotations:
    pkg/source: e2fsprogs/e2fslibs
    pkg/version: 1.42.13-1ubuntu1.2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8d165ef1e40c7ee656a82f97f28c66a7a81e2ed5
  description: ""
  annotations:
    pkg/source: e2fsprogs/libcomerr2
    pkg/version: 1.42.13-1ubuntu1.2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 1dd6ee12a049a651dadcdc3706971759c9a51130
  description: ""
  annotations:
    pkg/source: e2fsprogs/libss2
    pkg/version: 1.42.13-1ubuntu1.2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 2ad4b4ce059e470897c177aa0d28a1c7a54b39c6
  description: ""
  annotations:
    pkg/source: findutils
    pkg/version: 4.6.0+git+20160126-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e824c56c3385f199752e13c8a0cd0ca0935c382c
  description: ""
  annotations:
    pkg/source: gcc-5/gcc-5-base
    pkg/version: 5.4.0-6ubuntu1~16.04.12
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9758f01f127070f04f3d202e00da20c8c18af64c
  description: ""
  annotations:
    pkg/source: gcc-5/libstdc++6
    pkg/version: 5.4.0-6ubuntu1~16.04.12
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 945d73887363eb9560140d01738c27275ad0e381
  description: ""
  annotations:
    pkg/source: gccgo-6/gcc-6-base
    pkg/version: 6.0.1-0ubuntu1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 7fc991d9951809dc883a7ec77b9e3a948f506efb
  description: ""
  annotations:
    pkg/source: gccgo-6/libgcc1
    pkg/version: 1:6.0.1-0ubuntu1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ae478bbd770c5614ab3a42b4c66cc520688d230f
  description: ""
  annotations:
    pkg/source: glibc/libc-bin
    pkg/version: 2.23-0ubuntu11.3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 1d12cc7b7a067326d4cc25bba5c72c4b863499e9
  description: ""
  annotations:
    pkg/source: glibc/libc6
    pkg/version: 2.23-0ubuntu11.3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c5f52553890edf3fb94d315ec7a17da52e43ba51
  description: ""
  annotations:
    pkg/source: glibc/multiarch-support
    pkg/version: 2.23-0ubuntu11.3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 1b9955f1ad4959d1d40cbe27cd7ca744939d0bd1
  description: ""
  annotations:
    pkg/source: gnupg
    pkg/version: 1.4.20-1ubuntu3.3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ab675efc85a9f03b68909f1b0de40216f0a7f251
  description: ""
  annotations:
    pkg/source: gnupg/gpgv
    pkg/version: 1.4.20-1ubuntu3.3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 10142eaecf2104ac3674ce4996dc4bafc94d477e
  description: ""
  annotations:
    pkg/source: grep
    pkg/version: 2.25-1~16.04.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ebc464550d23535d83c6945b1309ded08725be17
  description: ""
  annotations:
    pkg/source: gzip
    pkg/version: 1.6-4ubuntu1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 94bd5bbb22ee35e4c8893a27754b06bacbd64a40
  description: ""
  annotations:
    pkg/source: hostname
    pkg/version: 3.16ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 1055b5908c4d4130f24ed48a42921b27977d5492
  description: ""
  annotations:
    pkg/source: init-system-helpers
    pkg/version: 1.29ubuntu4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a2b8f3297cefbba67b3564d8200979751ed79789
  description: ""
  annotations:
    pkg/source: init-system-helpers/init
    pkg/version: 1.29ubuntu4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: b54083dea3fdbfaa581c69da0f0bfa1696595b96
  description: ""
  annotations:
    pkg/source: insserv
    pkg/version: 1.14.0-5ubuntu3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fb64ed19a938e7413e035e61b0a253dd752d2ba2
  description: ""
  annotations:
    pkg/source: kmod/libkmod2
    pkg/version: 22-1ubuntu5.2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 6ef16e0118430bcf48f7530e4023b3acaa659c49
  description: ""
  annotations:
    pkg/source: libcap2
    pkg/version: 1:2.24-12
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 39ed105a8da7689392beb490777397a6f4238db8
  description: ""
  annotations:
    pkg/source: libcap2/libcap2-bin
    pkg/version: 1:2.24-12
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 74a820932623abe64fbacc5f803fb7ad384ceef0
  description: ""
  annotations:
    pkg/source: libgcrypt20
    pkg/version: 1.6.5-2ubuntu0.6
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 07d23c906f38c8abb46a2a670fd7e7e84ccef073
  description: ""
  annotations:
    pkg/source: libgpg-error/libgpg-error0
    pkg/version: 1.21-2ubuntu1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 2bedede2e3747e8d0b4ac354e4d80422bb54b700
  description: ""
  annotations:
    pkg/source: libseccomp/libseccomp2
    pkg/version: 2.5.1-1ubuntu1~16.04.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a4f803915db3c341c8438cf66d1fb3013fea7ce8
  description: ""
  annotations:
    pkg/source: libselinux/libselinux1
    pkg/version: 2.4-3build2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: b41ce2b8b68fbe41bf053120165acd7c3c57fae0
  description: ""
  annotations:
    pkg/source: libsemanage/libsemanage-common
    pkg/version: 2.3-1build3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 03602488f6ea1474b6fe5ecdd205d2cb5720c35f
  description: ""
  annotations:
    pkg/source: libsemanage/libsemanage1
    pkg/version: 2.3-1build3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 220a7c94b759aecf41e5285a268f9437195f0c01
  description: ""
  annotations:
    pkg/source: libsepol/libsepol1
    pkg/version: 2.4-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 36259897d24ff5739a6ed5ba24be40633589c2ae
  description: ""
  annotations:
    pkg/source: libusb/libusb-0.1-4
    pkg/version: 2:0.1.12-28
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 920aace258f8102767969ca87bad00aa05a6a8fb
  description: ""
  annotations:
    pkg/source: libzstd/libzstd1
    pkg/version: 1.3.1+dfsg-1~ubuntu0.16.04.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 5ce23764e37da4473898f8a1dccb99f0b09dcdc0
  description: ""
  annotations:
    pkg/source: lsb/lsb-base
    pkg/version: 9.20160110ubuntu0.2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8553c3a1eabb5f3295c2ed05b2983e182414acb5
  description: ""
  annotations:
    pkg/source: lvm2/libdevmapper1.02.1
    pkg/version: 2:1.02.110-1ubuntu10
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c47a0eba4ee87a9dd866dc92c5dcc54ab210cedf
  description: ""
  annotations:
    pkg/source: lz4/liblz4-1
    pkg/version: 0.0~r131-2ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 7eb691e301dc034329a0ab6e7160975fd61e2abe
  description: ""
  annotations:
    pkg/source: makedev
    pkg/version: 2.3.1-93ubuntu2~ubuntu16.04.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9fd1bb6fa3f54922b2c3892c1cb55e1d1f9e9ee3
  description: ""
  annotations:
    pkg/source: mawk
    pkg/version: 1.3.3-17ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 2035e5979be5cac41e64da612ea10461f7916026
  description: ""
  annotations:
    pkg/source: meta-common-packages
    pkg/version: meta
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 6e0ef3af1c9ca4170c72514daf6bdd63cd5a09b8
  description: ""
  annotations:
    pkg/source: ncurses/libncurses5
    pkg/version: 6.0+20160213-1ubuntu1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 089bdc03e4b9d3f0a4916cdc028b2f6ed4c59fdd
  description: ""
  annotations:
    pkg/source: ncurses/libncursesw5
    pkg/version: 6.0+20160213-1ubuntu1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 50940957757950ef4bf948227211001c570e4027
  description: ""
  annotations:
    pkg/source: ncurses/libtinfo5
    pkg/version: 6.0+20160213-1ubuntu1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bd59ce435dd89a14b01246398b34d25d93d71124
  description: ""
  annotations:
    pkg/source: ncurses/ncurses-base
    pkg/version: 6.0+20160213-1ubuntu1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 946b7e22eb4c0d214b9c0f226e44c33b33f54199
  description: ""
  annotations:
    pkg/source: ncurses/ncurses-bin
    pkg/version: 6.0+20160213-1ubuntu1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c58792f516e0527883dac15ad50678f31be4650f
  description: ""
  annotations:
    pkg/source: pam/libpam-modules
    pkg/version: 1.1.8-3.2ubuntu2.3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ef72a6eefc3a89f3ea55bc8c14c0ebd79a8d0716
  description: ""
  annotations:
    pkg/source: pam/libpam-modules-bin
    pkg/version: 1.1.8-3.2ubuntu2.3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 963c8ad5c9063394ad89fc8f9a0ce5e3667e006b
  description: ""
  annotations:
    pkg/source: pam/libpam-runtime
    pkg/version: 1.1.8-3.2ubuntu2.3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bb2923af364db2e904de30a79e0c783482e8e98f
  description: ""
  annotations:
    pkg/source: pam/libpam0g
    pkg/version: 1.1.8-3.2ubuntu2.3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 565b07784c0fdccbbddee616feaad93f2da89a14
  description: ""
  annotations:
    pkg/source: pcre3/libpcre3
    pkg/version: 2:8.38-3.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8a604aa328fcf21b966f7ea454cc3d7974f11b20
  description: ""
  annotations:
    pkg/source: perl/perl-base
    pkg/version: 5.22.1-9ubuntu0.9
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 69dc44e5eebb2695a1be95fabae86de3a78be24f
  description: ""
  annotations:
    pkg/source: procps
    pkg/version: 2:3.3.10-4ubuntu2.5
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 884c4b2ec360712c3e8fd62cb8ab62b10dd9230e
  description: ""
  annotations:
    pkg/source: procps/libprocps4
    pkg/version: 2:3.3.10-4ubuntu2.5
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 08d05424595394097cfae587f9646a4bbdab85bf
  description: ""
  annotations:
    pkg/source: readline6/libreadline6
    pkg/version: 6.3-8ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 5b77f3bb7c3dc758e536210fb1165e96c6d09146
  description: ""
  annotations:
    pkg/source: readline6/readline-common
    pkg/version: 6.3-8ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fe32fdb72c437c468daa1e2a8c3f90949156e36f
  description: ""
  annotations:
    pkg/source: sed
    pkg/version: 4.2.2-7
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a9609ddf2c8399a1b1b258b9b0846f4953abdac9
  description: ""
  annotations:
    pkg/source: sensible-utils
    pkg/version: 0.0.9ubuntu0.16.04.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 1b736716594c259214690225bf603184b7a34baa
  description: ""
  annotations:
    pkg/source: shadow/login
    pkg/version: 1:4.2-3.1ubuntu5.4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e3ac57ae9b569d880967aa838471610bfdabcc53
  description: ""
  annotations:
    pkg/source: shadow/passwd
    pkg/version: 1:4.2-3.1ubuntu5.4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 3292aa08b7730aab607aa1b730e5982df732b791
  description: ""
  annotations:
    pkg/source: systemd
    pkg/version: 229-4ubuntu21.31
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c33ee74a12aaae6ff0d76db450d6090fe4f62509
  description: ""
  annotations:
    pkg/source: systemd/libsystemd0
    pkg/version: 229-4ubuntu21.31
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c71f87f5941e5bd03a232e09a620bea37294f3f7
  description: ""
  annotations:
    pkg/source: systemd/libudev1
    pkg/version: 229-4ubuntu21.31
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 42d8ded84ee7b4299d34adf9346ca1b7f07eee45
  description: ""
  annotations:
    pkg/source: systemd/systemd-sysv
    pkg/version: 229-4ubuntu21.31
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4fa76f79702aa3437fa2c40d277b14607854ffaf
  description: ""
  annotations:
    pkg/source: sysvinit/initscripts
    pkg/version: 2.88dsf-59.3ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 316114cc9dc873788721894c1e03d19e8e35c006
  description: ""
  annotations:
    pkg/source: sysvinit/sysv-rc
    pkg/version: 2.88dsf-59.3ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8c03abdcf253860c67d400c02a9ea97601d8ad27
  description: ""
  annotations:
    pkg/source: sysvinit/sysvinit-utils
    pkg/version: 2.88dsf-59.3ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: d8346ddb5308d939922deb0a19a004956c91858d
  description: ""
  annotations:
    pkg/source: tar
    pkg/version: 1.28-2.1ubuntu0.2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c97b11457195e8e89afd73233170cc3e7f99a66c
  description: ""
  annotations:
    pkg/source: ubuntu-keyring
    pkg/version: 2012.05.19.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 38c341c61af0ac8ff46cabb9d8edeecd195ef98d
  description: ""
  annotations:
    pkg/source: ustr/libustr-1.0-1
    pkg/version: 1.0.4-5
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 21dba9f8c0296a3fa4e230e89a1ed5de100003bc
  description: ""
  annotations:
    pkg/source: util-linux
    pkg/version: 2.27.1-6ubuntu3.10
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fa65fd3d352ec4299eca7ad08f971e2eda1a94a4
  description: ""
  annotations:
    pkg/source: util-linux/bsdutils
    pkg/version: 1:2.27.1-6ubuntu3.10
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 38fd634ba2c6f9c199c68410e14cf3145ce8f5a1
  description: ""
  annotations:
    pkg/source: util-linux/libblkid1
    pkg/version: 2.27.1-6ubuntu3.10
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9419fa62e3fa144518b54c5353533aa7e272233d
  description: ""
  annotations:
    pkg/source: util-linux/libfdisk1
    pkg/version: 2.27.1-6ubuntu3.10
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 583c0f6c61babb2a2b3368505dc9713c58aaf7fc
  description: ""
  annotations:
    pkg/source: util-linux/libmount1
    pkg/version: 2.27.1-6ubuntu3.10
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 3f63a06b51c363ceecdc7f0d1fe5cecf3c413f21
  description: ""
  annotations:
    pkg/source: util-linux/libsmartcols1
    pkg/version: 2.27.1-6ubuntu3.10
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 239885b837196fa41fd89e78520cffedb0b18f0c
  description: ""
  annotations:
    pkg/source: util-linux/libuuid1
    pkg/version: 2.27.1-6ubuntu3.10
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 7f9aebe06429c8a9ea79a2b90c0fb4838967260a
  description: ""
  annotations:
    pkg/source: util-linux/mount
    pkg/version: 2.27.1-6ubuntu3.10
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e368037074124a5492c4ede34d90ed39c90961ed
  description: ""
  annotations:
    pkg/source: xz-utils/liblzma5
    pkg/version: 5.1.1alpha+20120614-2ubuntu2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 66902dd681057de76d6a0932a92036b0cf88ecbc
  description: ""
  annotations:
    pkg/source: zlib/zlib1g
    pkg/version: 1:1.2.8.dfsg-2ubuntu4.3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 6178b951d103fc74c16a220a1411975be05a9002
  description: ""
  annotations:
    pkg/base_image: ubuntu:xenial
    pkg/browse_url: https://app.snyk.io/org/pkman92/project/98f4c7a7-ce0e-4016-8a4d-505a0ccf0719
    pkg/image_tag: xenial
    pkg/repo: pkman92/kubernetes
    pkg/source: cluster/gce/gci/mounter/Dockerfile
    pkg/vulnerabilities: '{"low":46,"medium":8,"high":1,"critical":0}'
spec:
  type: service
  lifecycle: experimental
  system: domain-1
  owner: dockerfile
  dependsOn:
  - Component:default/809462d8cb5d7b33108c7c2bac3a0d630c3cc9e3
  - Component:default/308ff95d1c9ce24aaf07363a06f0cc3d071b6af3
  - Component:default/7f6365b20b953da660b0e4a8d5306a9a828a0c7a
  - Component:default/5f352b8079e455f15849454ea39b2e6d889e1479
  - Component:default/15f84e5f478605045590e85dc63b689b9f5e0af0
  - Component:default/9e4a5d1440c9b75b8d6b841dc003022a61d0566d
  - Component:default/226f70b09bc1ec4eb9554c3c28fd9fb6a85c659c
  - Component:default/383949a0fbcad08a01f22964a29473316e0df7b7
  - Component:default/2ed6919b09992a03f1ef084e9cf4209e8439b6d1
  - Component:default/667beefbcc6515e67a2fac41446077b9929b0b0e
  - Component:default/49ee0e15427d89b5b4ce4de82a5e18edf765681a
  - Component:default/87f38c10e11c7a57a36115ea0ffd1c38f3e911dd
  - Component:default/9255304e7dccf0e2d1cbbf01b772cfba30bab192
  - Component:default/78363161b5a11cc53f55d02ebe3aaeccfbc97cb3
  - Component:default/7e07b7c9dad078ff9741691547ca516899f50559
  - Component:default/dd8bc6a839375048f3b980610dca85c5e7d18635
  - Component:default/a471687768f7f2023e4db381d7e28e3955a5d85f
  - Component:default/8a106462b7ddc3a7a1143c929648406214d3a1f2
  - Component:default/bbd43afdaa0a583f020e1db0081883c1ab8b4642
  - Component:default/a67752bbab3c985170234fa03216c843e719ff56
  - Component:default/dc134b884e2ae5efb03d5f0be24eb7c3998067d5
  - Component:default/02e99874c6833a885ba0b5523acacef29b3d2ddb
  - Component:default/79295311f9ae2a1be7b43fd8dbb5b1ca5cd33e37
  - Component:default/33ed539c7a77c708640ab918a0320805d1b32206
  - Component:default/8d165ef1e40c7ee656a82f97f28c66a7a81e2ed5
  - Component:default/1dd6ee12a049a651dadcdc3706971759c9a51130
  - Component:default/2ad4b4ce059e470897c177aa0d28a1c7a54b39c6
  - Component:default/e824c56c3385f199752e13c8a0cd0ca0935c382c
  - Component:default/9758f01f127070f04f3d202e00da20c8c18af64c
  - Component:default/945d73887363eb9560140d01738c27275ad0e381
  - Component:default/7fc991d9951809dc883a7ec77b9e3a948f506efb
  - Component:default/ae478bbd770c5614ab3a42b4c66cc520688d230f
  - Component:default/1d12cc7b7a067326d4cc25bba5c72c4b863499e9
  - Component:default/c5f52553890edf3fb94d315ec7a17da52e43ba51
  - Component:default/1b9955f1ad4959d1d40cbe27cd7ca744939d0bd1
  - Component:default/ab675efc85a9f03b68909f1b0de40216f0a7f251
  - Component:default/10142eaecf2104ac3674ce4996dc4bafc94d477e
  - Component:default/ebc464550d23535d83c6945b1309ded08725be17
  - Component:default/94bd5bbb22ee35e4c8893a27754b06bacbd64a40
  - Component:default/1055b5908c4d4130f24ed48a42921b27977d5492
  - Component:default/a2b8f3297cefbba67b3564d8200979751ed79789
  - Component:default/b54083dea3fdbfaa581c69da0f0bfa1696595b96
  - Component:default/fb64ed19a938e7413e035e61b0a253dd752d2ba2
  - Component:default/6ef16e0118430bcf48f7530e4023b3acaa659c49
  - Component:default/39ed105a8da7689392beb490777397a6f4238db8
  - Component:default/74a820932623abe64fbacc5f803fb7ad384ceef0
  - Component:default/07d23c906f38c8abb46a2a670fd7e7e84ccef073
  - Component:default/2bedede2e3747e8d0b4ac354e4d80422bb54b700
  - Component:default/a4f803915db3c341c8438cf66d1fb3013fea7ce8
  - Component:default/b41ce2b8b68fbe41bf053120165acd7c3c57fae0
  - Component:default/03602488f6ea1474b6fe5ecdd205d2cb5720c35f
  - Component:default/220a7c94b759aecf41e5285a268f9437195f0c01
  - Component:default/36259897d24ff5739a6ed5ba24be40633589c2ae
  - Component:default/920aace258f8102767969ca87bad00aa05a6a8fb
  - Component:default/5ce23764e37da4473898f8a1dccb99f0b09dcdc0
  - Component:default/8553c3a1eabb5f3295c2ed05b2983e182414acb5
  - Component:default/c47a0eba4ee87a9dd866dc92c5dcc54ab210cedf
  - Component:default/7eb691e301dc034329a0ab6e7160975fd61e2abe
  - Component:default/9fd1bb6fa3f54922b2c3892c1cb55e1d1f9e9ee3
  - Component:default/2035e5979be5cac41e64da612ea10461f7916026
  - Component:default/6e0ef3af1c9ca4170c72514daf6bdd63cd5a09b8
  - Component:default/089bdc03e4b9d3f0a4916cdc028b2f6ed4c59fdd
  - Component:default/50940957757950ef4bf948227211001c570e4027
  - Component:default/bd59ce435dd89a14b01246398b34d25d93d71124
  - Component:default/946b7e22eb4c0d214b9c0f226e44c33b33f54199
  - Component:default/c58792f516e0527883dac15ad50678f31be4650f
  - Component:default/ef72a6eefc3a89f3ea55bc8c14c0ebd79a8d0716
  - Component:default/963c8ad5c9063394ad89fc8f9a0ce5e3667e006b
  - Component:default/bb2923af364db2e904de30a79e0c783482e8e98f
  - Component:default/565b07784c0fdccbbddee616feaad93f2da89a14
  - Component:default/8a604aa328fcf21b966f7ea454cc3d7974f11b20
  - Component:default/69dc44e5eebb2695a1be95fabae86de3a78be24f
  - Component:default/884c4b2ec360712c3e8fd62cb8ab62b10dd9230e
  - Component:default/08d05424595394097cfae587f9646a4bbdab85bf
  - Component:default/5b77f3bb7c3dc758e536210fb1165e96c6d09146
  - Component:default/fe32fdb72c437c468daa1e2a8c3f90949156e36f
  - Component:default/a9609ddf2c8399a1b1b258b9b0846f4953abdac9
  - Component:default/1b736716594c259214690225bf603184b7a34baa
  - Component:default/e3ac57ae9b569d880967aa838471610bfdabcc53
  - Component:default/3292aa08b7730aab607aa1b730e5982df732b791
  - Component:default/c33ee74a12aaae6ff0d76db450d6090fe4f62509
  - Component:default/c71f87f5941e5bd03a232e09a620bea37294f3f7
  - Component:default/42d8ded84ee7b4299d34adf9346ca1b7f07eee45
  - Component:default/4fa76f79702aa3437fa2c40d277b14607854ffaf
  - Component:default/316114cc9dc873788721894c1e03d19e8e35c006
  - Component:default/8c03abdcf253860c67d400c02a9ea97601d8ad27
  - Component:default/d8346ddb5308d939922deb0a19a004956c91858d
  - Component:default/c97b11457195e8e89afd73233170cc3e7f99a66c
  - Component:default/38c341c61af0ac8ff46cabb9d8edeecd195ef98d
  - Component:default/21dba9f8c0296a3fa4e230e89a1ed5de100003bc
  - Component:default/fa65fd3d352ec4299eca7ad08f971e2eda1a94a4
  - Component:default/38fd634ba2c6f9c199c68410e14cf3145ce8f5a1
  - Component:default/9419fa62e3fa144518b54c5353533aa7e272233d
  - Component:default/583c0f6c61babb2a2b3368505dc9713c58aaf7fc
  - Component:default/3f63a06b51c363ceecdc7f0d1fe5cecf3c413f21
  - Component:default/239885b837196fa41fd89e78520cffedb0b18f0c
  - Component:default/7f9aebe06429c8a9ea79a2b90c0fb4838967260a
  - Component:default/e368037074124a5492c4ede34d90ed39c90961ed
  - Component:default/66902dd681057de76d6a0932a92036b0cf88ecbc
