apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 793fa24fa578044dc6bfffc0a932e10ff3a928bd
  description: ""
  annotations:
    pkg/source: packages/cli/asset-types/package.json
    pkg/version: ""
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 793fa24fa578044dc6bfffc0a932e10ff3a928bd
  description: ""
  annotations:
    pkg/source: packages/cli/asset-types/package.json
    pkg/vulnerabilities: '{"low":0,"medium":0,"high":0,"critical":0}'
spec:
  type: service
  lifecycle: experimental
  system: domain-1
  owner: yarn
  dependsOn:
  - Component:default/793fa24fa578044dc6bfffc0a932e10ff3a928bd
