apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c9d62e7acf81bda9d78f3567df463e9ec2077476
  description: ""
  annotations:
    pkg/source: '@backstage/errors'
    pkg/version: 0.2.0
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4f4f8b2b6aabb90ee254954db7029aee645a933f
  description: ""
  annotations:
    pkg/source: '@backstage/types'
    pkg/version: ^0.1.1
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eb9ec0d32553fd7e41b9721b27b6ebbf17c0081b
  description: ""
  annotations:
    pkg/source: tr46
    pkg/version: 0.0.3
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c2716f46306f1387acb3317c6f6d3a980db8ac98
  description: ""
  annotations:
    pkg/source: webidl-conversions
    pkg/version: 3.0.1
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 222b17d28468cf4fc2c2dcf305a129c0be65f0cd
  description: ""
  annotations:
    pkg/source: whatwg-url
    pkg/version: 5.0.0
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cb38786f845c724406f632a5fa232107f429d878
  description: ""
  annotations:
    pkg/source: node-fetch
    pkg/version: 2.6.7
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 239a720df7660059cb0853be0a993e2e2fee19ef
  description: ""
  annotations:
    pkg/source: cross-fetch
    pkg/version: 3.1.5
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 37f3420b1ad43ed11dc9ad820ddfcc0e2b198a18
  description: ""
  annotations:
    pkg/source: type-fest
    pkg/version: 0.20.2
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e645c3befc446e4f86e10432d674e331eb468df4
  description: ""
  annotations:
    pkg/source: serialize-error
    pkg/version: 8.1.0
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 738ba257c841894c23b31d505016a9f3a4719035
  description: ""
  annotations:
    pkg/base_image: ""
    pkg/browse_url: https://app.snyk.io/org/pkman92/project/2b705923-ab7a-4b77-8f26-cab77ea7cded
    pkg/image_tag: 0.2.0
    pkg/repo: pkman92/backstage
    pkg/source: packages/errors/package.json
    pkg/vulnerabilities: '{"low":0,"medium":0,"high":0,"critical":0}'
spec:
  type: service
  lifecycle: experimental
  system: domain-1
  owner: yarn
  dependsOn:
  - Component:default/c9d62e7acf81bda9d78f3567df463e9ec2077476
  - Component:default/4f4f8b2b6aabb90ee254954db7029aee645a933f
  - Component:default/eb9ec0d32553fd7e41b9721b27b6ebbf17c0081b
  - Component:default/c2716f46306f1387acb3317c6f6d3a980db8ac98
  - Component:default/222b17d28468cf4fc2c2dcf305a129c0be65f0cd
  - Component:default/cb38786f845c724406f632a5fa232107f429d878
  - Component:default/239a720df7660059cb0853be0a993e2e2fee19ef
  - Component:default/37f3420b1ad43ed11dc9ad820ddfcc0e2b198a18
  - Component:default/e645c3befc446e4f86e10432d674e331eb468df4
