apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ede01019cbf075a774cdcc3396ee1da269dad1a7
  description: ""
  annotations:
    pkg/source: debian
    pkg/version: latest
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 0b5511d4c34ce9286e6b10b703c121073069f539
  description: ""
  annotations:
    pkg/source: acl/libacl1
    pkg/version: 2.2.53-10
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 72aabfa093a1615acb171b4f60b9642639f73552
  description: ""
  annotations:
    pkg/source: adduser
    pkg/version: "3.118"
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 715d971a5d041f13170d99654a6dc242b28c7818
  description: ""
  annotations:
    pkg/source: apt
    pkg/version: 2.2.4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: f58bcd93a632647cfdeb39ac403b95125e5b9090
  description: ""
  annotations:
    pkg/source: apt/libapt-pkg6.0
    pkg/version: 2.2.4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 49286ba07fdd0b5ae2a4c4180def8f23c4932286
  description: ""
  annotations:
    pkg/source: attr/libattr1
    pkg/version: 1:2.4.48-6
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 47d29ab26ff078a32fa0144c460d7ec586403e67
  description: ""
  annotations:
    pkg/source: audit/libaudit-common
    pkg/version: 1:3.0-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: b2f608d194a6a78cbc091ba94a98d4178650c485
  description: ""
  annotations:
    pkg/source: audit/libaudit1
    pkg/version: 1:3.0-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8ccb565114ce132b3b21bd59a46fea265b311756
  description: ""
  annotations:
    pkg/source: base-files
    pkg/version: 11.1+deb11u2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 3221c290c07d16425324a37dd345ab4759d362e3
  description: ""
  annotations:
    pkg/source: base-passwd
    pkg/version: 3.5.51
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bcdc5d9d305dcb0e13b1520fe9f46b7f3e03dda8
  description: ""
  annotations:
    pkg/source: bash/bash
    pkg/version: 5.1-2+b3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 024c5b5fe89f1af36dae4914a31784c298d5f803
  description: ""
  annotations:
    pkg/source: bzip2/libbz2-1.0
    pkg/version: 1.0.8-4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 125e79d0d0111dc895dcf925731c59ed3b98a339
  description: ""
  annotations:
    pkg/source: cdebconf/libdebconfclient0
    pkg/version: "0.260"
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 204cbd7fd00018fc3303b0460d13df71ec4b4383
  description: ""
  annotations:
    pkg/source: coreutils/coreutils
    pkg/version: 8.32-4+b1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 0edfd3a00c51b15de3d938a8d8a004c2a67201ad
  description: ""
  annotations:
    pkg/source: dash
    pkg/version: 0.5.11+git20200708+dd9ef66-5
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 0a4021c4826440fb57e76042272f4e4188f71573
  description: ""
  annotations:
    pkg/source: db5.3/libdb5.3
    pkg/version: 5.3.28+dfsg1-0.8
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c65a02e2c3a5017659f1c91daf970665d525e296
  description: ""
  annotations:
    pkg/source: debconf
    pkg/version: 1.5.77
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 000c004bd1b1a5a6f5788e6f431e5c97ab53ec90
  description: ""
  annotations:
    pkg/source: debian-archive-keyring
    pkg/version: 2021.1.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 5ec95ca322f69255ee43fa6fd9f95581e85967aa
  description: ""
  annotations:
    pkg/source: debianutils
    pkg/version: 4.11.2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: beaa205a06795c29939e2ff77afa4c273790cef5
  description: ""
  annotations:
    pkg/source: diffutils
    pkg/version: 1:3.7-5
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bad76f2fea34f69429a891f264e39524d3836177
  description: ""
  annotations:
    pkg/source: dpkg
    pkg/version: 1.20.9
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 46076f7d4afaa38fee0226152de67becd18464f9
  description: ""
  annotations:
    pkg/source: e2fsprogs
    pkg/version: 1.46.2-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bd087ce355bbdb93a530bcb12b34779867cbf6da
  description: ""
  annotations:
    pkg/source: e2fsprogs/libcom-err2
    pkg/version: 1.46.2-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 44901dec26326999e339e9c536a1488e967b5a76
  description: ""
  annotations:
    pkg/source: e2fsprogs/libext2fs2
    pkg/version: 1.46.2-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a46a37f4ebf73266165f3c604216fda94171fb80
  description: ""
  annotations:
    pkg/source: e2fsprogs/libss2
    pkg/version: 1.46.2-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9c693fe630cb47cbd7a36bb34e5654808402198a
  description: ""
  annotations:
    pkg/source: e2fsprogs/logsave
    pkg/version: 1.46.2-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bc2e3ff8971dcf7b7f077a7993ae2ee4e4f99443
  description: ""
  annotations:
    pkg/source: findutils
    pkg/version: 4.8.0-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 11a7a814ad635935422577f3c6fd370cf65297a8
  description: ""
  annotations:
    pkg/source: gcc-10/gcc-10-base
    pkg/version: 10.2.1-6
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e2289c1302e9b5051a768b2f11d17d0c77eeda1f
  description: ""
  annotations:
    pkg/source: gcc-10/libgcc-s1
    pkg/version: 10.2.1-6
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 12be24b8441f4998fb67709a0af53f20e3c9aa23
  description: ""
  annotations:
    pkg/source: gcc-10/libstdc++6
    pkg/version: 10.2.1-6
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c3a92598c2bff2af5131f1b36903d1bac49ccc89
  description: ""
  annotations:
    pkg/source: gcc-9/gcc-9-base
    pkg/version: 9.3.0-22
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 02ef0fe7ae80ebb25b8c8b52e2ac3bfadfb74a05
  description: ""
  annotations:
    pkg/source: glibc/libc-bin
    pkg/version: 2.31-13+deb11u2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 2b8716bcb8e4d11fdb8618e4af811dc51bb6eca9
  description: ""
  annotations:
    pkg/source: glibc/libc6
    pkg/version: 2.31-13+deb11u2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8cc20e6cfa81f4dcd79d23a224dc04796f190ad6
  description: ""
  annotations:
    pkg/source: gmp/libgmp10
    pkg/version: 2:6.2.1+dfsg-1+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 312b4891e2e2b6e028c38ead859b578f24c4afd1
  description: ""
  annotations:
    pkg/source: gnupg2/gpgv
    pkg/version: 2.2.27-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 5af3f8e4482edc048e3669f14ee8fdc8e025afcc
  description: ""
  annotations:
    pkg/source: gnutls28/libgnutls30
    pkg/version: 3.7.1-5
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bf4fd1665682d7e4ca98f69ce0f45ed688272812
  description: ""
  annotations:
    pkg/source: grep
    pkg/version: 3.6-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 404e5409408e0cf7b2c300b018b563892531058e
  description: ""
  annotations:
    pkg/source: gzip
    pkg/version: 1.10-4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 65d052648269269467b20c18cb5b8fe3fd995098
  description: ""
  annotations:
    pkg/source: hostname
    pkg/version: "3.23"
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 28334d4d7c71fc5272573bbc95dfd968f12c82a3
  description: ""
  annotations:
    pkg/source: init-system-helpers
    pkg/version: "1.60"
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a00eee579edacb32e22e0e95073c7a1ec14f4ad0
  description: ""
  annotations:
    pkg/source: keyutils/libkeyutils1
    pkg/version: 1.6.1-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 426a3cfeb29fc2885350cf8d826b9b2744fd1032
  description: ""
  annotations:
    pkg/source: krb5/libgssapi-krb5-2
    pkg/version: 1.18.3-6+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4caa42e3ab0f9acfef07ba20464b3e170ad19284
  description: ""
  annotations:
    pkg/source: krb5/libk5crypto3
    pkg/version: 1.18.3-6+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 5e2ec9ee13d53f4035d473f071d59a4fe7de221f
  description: ""
  annotations:
    pkg/source: krb5/libkrb5-3
    pkg/version: 1.18.3-6+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 11ff77fe208119a56605f0ca6d10413d53a10e4b
  description: ""
  annotations:
    pkg/source: krb5/libkrb5support0
    pkg/version: 1.18.3-6+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 12121dee10657c43bb4b02ee8ed8125e88953442
  description: ""
  annotations:
    pkg/source: libcap-ng/libcap-ng0
    pkg/version: 0.7.9-2.2+b1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a5bbca3bcf240b830266b0f27a4da61101ae75e9
  description: ""
  annotations:
    pkg/source: libffi/libffi7
    pkg/version: 3.3-6
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 98664cbf4b50478649b53095b5ddc6ff439978b9
  description: ""
  annotations:
    pkg/source: libgcrypt20
    pkg/version: 1.8.7-6
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8c02a7a198f1f04f87d433177e1a89314776bddc
  description: ""
  annotations:
    pkg/source: libgpg-error/libgpg-error0
    pkg/version: 1.38-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c500527766c732049cf602fa3bcae58f8e6c4efc
  description: ""
  annotations:
    pkg/source: libidn2/libidn2-0
    pkg/version: 2.3.0-5
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 46f89f84cbc0834c28057395e5ebf63f2e0337c5
  description: ""
  annotations:
    pkg/source: libnsl/libnsl2
    pkg/version: 1.3.0-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 05bf1735753b5dffa72db2d38b715e18740b3f47
  description: ""
  annotations:
    pkg/source: libseccomp/libseccomp2
    pkg/version: 2.5.1-1+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c54ed8022f5db78977a59efc75c10a05ee16f109
  description: ""
  annotations:
    pkg/source: libselinux/libselinux1
    pkg/version: 3.1-3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eba0e8a7035bd3fa86cd24bd5387425bfed617d4
  description: ""
  annotations:
    pkg/source: libsemanage/libsemanage-common
    pkg/version: 3.1-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e03e7e542e356d18f90440a4a5d6261e1972d346
  description: ""
  annotations:
    pkg/source: libsemanage/libsemanage1
    pkg/version: 3.1-1+b2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: f201386beb45b093937fc803ce53dd905b0bd971
  description: ""
  annotations:
    pkg/source: libsepol/libsepol1
    pkg/version: 3.1-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8aca16a253beb3ea1c235ee105e49a9923d000b9
  description: ""
  annotations:
    pkg/source: libtasn1-6
    pkg/version: 4.16.0-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a35d8347890c829b7e9530c6f84e29db57690d3c
  description: ""
  annotations:
    pkg/source: libtirpc/libtirpc-common
    pkg/version: 1.3.1-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e6eaae2b3b3cf67c7bf13e48dc79fff348a00344
  description: ""
  annotations:
    pkg/source: libtirpc/libtirpc3
    pkg/version: 1.3.1-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 05dfbb2469a77dce42ea1452fd85d8f060f12701
  description: ""
  annotations:
    pkg/source: libunistring/libunistring2
    pkg/version: 0.9.10-4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 53344371e58b2b00b8d146711821f13595cab6c4
  description: ""
  annotations:
    pkg/source: libxcrypt/libcrypt1
    pkg/version: 1:4.4.18-4
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 7489214fe02ba6ba64c1250d4c14e3340bbd7f0b
  description: ""
  annotations:
    pkg/source: libzstd/libzstd1
    pkg/version: 1.4.8+dfsg-2.1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 1af346b2f1c50b749048b3093f2f5797ea9baa8d
  description: ""
  annotations:
    pkg/source: lsb/lsb-base
    pkg/version: 11.1.0
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e1d2a0c945b35720247c5da666751df1390354a1
  description: ""
  annotations:
    pkg/source: lz4/liblz4-1
    pkg/version: 1.9.3-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 05aa47bf5c76c26a7d277f9f9ec4a08100de1b6a
  description: ""
  annotations:
    pkg/source: mawk
    pkg/version: 1.3.4.20200120-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 2035e5979be5cac41e64da612ea10461f7916026
  description: ""
  annotations:
    pkg/source: meta-common-packages
    pkg/version: meta
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 19e742349865f76734857900e11d2cdc51c66228
  description: ""
  annotations:
    pkg/source: ncurses/libtinfo6
    pkg/version: 6.2+20201114-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a4d6531c838310c9caa7ab618de18c9aa930a7c8
  description: ""
  annotations:
    pkg/source: ncurses/ncurses-base
    pkg/version: 6.2+20201114-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 841c6e9211e7e907e33db5201eafbf9a47599a3e
  description: ""
  annotations:
    pkg/source: ncurses/ncurses-bin
    pkg/version: 6.2+20201114-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9a665758631319f1c4b1ded550386a68f62cf623
  description: ""
  annotations:
    pkg/source: nettle/libhogweed6
    pkg/version: 3.7.3-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: d553d32172cb31613edf2e8544245fd20a7217c0
  description: ""
  annotations:
    pkg/source: nettle/libnettle8
    pkg/version: 3.7.3-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 1e9229ec940eae00119924e8a311508d8d2061c6
  description: ""
  annotations:
    pkg/source: openssl/libssl1.1
    pkg/version: 1.1.1k-1+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4d9a0f0043a8e565367ac33fe06348b4be2e013c
  description: ""
  annotations:
    pkg/source: p11-kit/libp11-kit0
    pkg/version: 0.23.22-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 753fae129437d0c3ec6183d9ac66b57623789549
  description: ""
  annotations:
    pkg/source: pam/libpam-modules
    pkg/version: 1.4.0-9+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 3fb0cf6850c8aa1624e42c1d6372d5d747dcee42
  description: ""
  annotations:
    pkg/source: pam/libpam-modules-bin
    pkg/version: 1.4.0-9+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: d8730214077ebaad7216c490b4d2fcc4fda3ef7d
  description: ""
  annotations:
    pkg/source: pam/libpam-runtime
    pkg/version: 1.4.0-9+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4a49c3bd15fe682f13b8bd190d546d993e43d858
  description: ""
  annotations:
    pkg/source: pam/libpam0g
    pkg/version: 1.4.0-9+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9e56163af492aeecf37a8d5c592a51de18f94fb4
  description: ""
  annotations:
    pkg/source: pcre2/libpcre2-8-0
    pkg/version: 10.36-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 44483eaa61bc0f090b4e62ad0ea20fd14282e80e
  description: ""
  annotations:
    pkg/source: pcre3/libpcre3
    pkg/version: 2:8.39-13
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 7e1be8946894b6ca93a7c18953f5d76a259243cd
  description: ""
  annotations:
    pkg/source: perl/perl-base
    pkg/version: 5.32.1-4+deb11u2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c3a5f34c21e76e37f3e3ce0e857f5f2e971de9a1
  description: ""
  annotations:
    pkg/source: sed
    pkg/version: 4.7-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 639f22d35c5f8366b935859ecfe2ed282a3912aa
  description: ""
  annotations:
    pkg/source: shadow/login
    pkg/version: 1:4.8.1-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4cbaa65d960c400c9b98f822ccc767f5a0e0bd31
  description: ""
  annotations:
    pkg/source: shadow/passwd
    pkg/version: 1:4.8.1-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 91c4113a7e8dfc7b7eebbc3d0cd5eecf0df170c6
  description: ""
  annotations:
    pkg/source: systemd/libsystemd0
    pkg/version: 247.3-6
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8089de52a3caa9ab4aa744f50f4264ca5ff9becd
  description: ""
  annotations:
    pkg/source: systemd/libudev1
    pkg/version: 247.3-6
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c60f1126e0c99535373a755f2a71082863cd0ae4
  description: ""
  annotations:
    pkg/source: sysvinit/sysvinit-utils
    pkg/version: 2.96-7
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: b6be0e3ec710848c729734ec71a55355ca2e50fa
  description: ""
  annotations:
    pkg/source: tar
    pkg/version: 1.34+dfsg-1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 69008417a9ca3897676992b312be3dc866b3df85
  description: ""
  annotations:
    pkg/source: tzdata
    pkg/version: 2021a-1+deb11u2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bd4817e3af1e8e1e175aa7270745d022da731f47
  description: ""
  annotations:
    pkg/source: util-linux
    pkg/version: 2.36.1-8+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a5d9340911e7e6a61c6e70ed22e855b28d21ac77
  description: ""
  annotations:
    pkg/source: util-linux/bsdutils
    pkg/version: 1:2.36.1-8+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 454e724a454306b909f1db2b8994c8a197f11011
  description: ""
  annotations:
    pkg/source: util-linux/libblkid1
    pkg/version: 2.36.1-8+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fd798c5dfd65c7bb38334f45c312f58d3073ea53
  description: ""
  annotations:
    pkg/source: util-linux/libmount1
    pkg/version: 2.36.1-8+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ba50f85d50670337ecf011b6276e2a6f3395b5c2
  description: ""
  annotations:
    pkg/source: util-linux/libsmartcols1
    pkg/version: 2.36.1-8+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 823eefb81f1613f6c8550d66b3174633f6ba7cc4
  description: ""
  annotations:
    pkg/source: util-linux/libuuid1
    pkg/version: 2.36.1-8+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 7bd65eb3ed83e0607ff6d945e35cb687dbf11a85
  description: ""
  annotations:
    pkg/source: util-linux/mount
    pkg/version: 2.36.1-8+deb11u1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ca31dd891d416bc3f4e68ba5edcf1e9399e93b6d
  description: ""
  annotations:
    pkg/source: xxhash/libxxhash0
    pkg/version: 0.8.0-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 2b640cb647696ea72f503252bee78419180f7428
  description: ""
  annotations:
    pkg/source: xz-utils/liblzma5
    pkg/version: 5.2.5-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: da1e754de291eb2eaac2420349485cc494e0556d
  description: ""
  annotations:
    pkg/source: zlib/zlib1g
    pkg/version: 1:1.2.11.dfsg-2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 963b913c78c860903f3dd85c16817096522cee48
  description: ""
  annotations:
    pkg/source: staging/src/k8s.io/client-go/examples/in-cluster-client-configuration/Dockerfile
    pkg/vulnerabilities: '{"low":37,"medium":1,"high":2,"critical":3}'
spec:
  type: service
  lifecycle: experimental
  system: domain-1
  owner: dockerfile
  dependsOn:
  - Component:default/ede01019cbf075a774cdcc3396ee1da269dad1a7
  - Component:default/0b5511d4c34ce9286e6b10b703c121073069f539
  - Component:default/72aabfa093a1615acb171b4f60b9642639f73552
  - Component:default/715d971a5d041f13170d99654a6dc242b28c7818
  - Component:default/f58bcd93a632647cfdeb39ac403b95125e5b9090
  - Component:default/49286ba07fdd0b5ae2a4c4180def8f23c4932286
  - Component:default/47d29ab26ff078a32fa0144c460d7ec586403e67
  - Component:default/b2f608d194a6a78cbc091ba94a98d4178650c485
  - Component:default/8ccb565114ce132b3b21bd59a46fea265b311756
  - Component:default/3221c290c07d16425324a37dd345ab4759d362e3
  - Component:default/bcdc5d9d305dcb0e13b1520fe9f46b7f3e03dda8
  - Component:default/024c5b5fe89f1af36dae4914a31784c298d5f803
  - Component:default/125e79d0d0111dc895dcf925731c59ed3b98a339
  - Component:default/204cbd7fd00018fc3303b0460d13df71ec4b4383
  - Component:default/0edfd3a00c51b15de3d938a8d8a004c2a67201ad
  - Component:default/0a4021c4826440fb57e76042272f4e4188f71573
  - Component:default/c65a02e2c3a5017659f1c91daf970665d525e296
  - Component:default/000c004bd1b1a5a6f5788e6f431e5c97ab53ec90
  - Component:default/5ec95ca322f69255ee43fa6fd9f95581e85967aa
  - Component:default/beaa205a06795c29939e2ff77afa4c273790cef5
  - Component:default/bad76f2fea34f69429a891f264e39524d3836177
  - Component:default/46076f7d4afaa38fee0226152de67becd18464f9
  - Component:default/bd087ce355bbdb93a530bcb12b34779867cbf6da
  - Component:default/44901dec26326999e339e9c536a1488e967b5a76
  - Component:default/a46a37f4ebf73266165f3c604216fda94171fb80
  - Component:default/9c693fe630cb47cbd7a36bb34e5654808402198a
  - Component:default/bc2e3ff8971dcf7b7f077a7993ae2ee4e4f99443
  - Component:default/11a7a814ad635935422577f3c6fd370cf65297a8
  - Component:default/e2289c1302e9b5051a768b2f11d17d0c77eeda1f
  - Component:default/12be24b8441f4998fb67709a0af53f20e3c9aa23
  - Component:default/c3a92598c2bff2af5131f1b36903d1bac49ccc89
  - Component:default/02ef0fe7ae80ebb25b8c8b52e2ac3bfadfb74a05
  - Component:default/2b8716bcb8e4d11fdb8618e4af811dc51bb6eca9
  - Component:default/8cc20e6cfa81f4dcd79d23a224dc04796f190ad6
  - Component:default/312b4891e2e2b6e028c38ead859b578f24c4afd1
  - Component:default/5af3f8e4482edc048e3669f14ee8fdc8e025afcc
  - Component:default/bf4fd1665682d7e4ca98f69ce0f45ed688272812
  - Component:default/404e5409408e0cf7b2c300b018b563892531058e
  - Component:default/65d052648269269467b20c18cb5b8fe3fd995098
  - Component:default/28334d4d7c71fc5272573bbc95dfd968f12c82a3
  - Component:default/a00eee579edacb32e22e0e95073c7a1ec14f4ad0
  - Component:default/426a3cfeb29fc2885350cf8d826b9b2744fd1032
  - Component:default/4caa42e3ab0f9acfef07ba20464b3e170ad19284
  - Component:default/5e2ec9ee13d53f4035d473f071d59a4fe7de221f
  - Component:default/11ff77fe208119a56605f0ca6d10413d53a10e4b
  - Component:default/12121dee10657c43bb4b02ee8ed8125e88953442
  - Component:default/a5bbca3bcf240b830266b0f27a4da61101ae75e9
  - Component:default/98664cbf4b50478649b53095b5ddc6ff439978b9
  - Component:default/8c02a7a198f1f04f87d433177e1a89314776bddc
  - Component:default/c500527766c732049cf602fa3bcae58f8e6c4efc
  - Component:default/46f89f84cbc0834c28057395e5ebf63f2e0337c5
  - Component:default/05bf1735753b5dffa72db2d38b715e18740b3f47
  - Component:default/c54ed8022f5db78977a59efc75c10a05ee16f109
  - Component:default/eba0e8a7035bd3fa86cd24bd5387425bfed617d4
  - Component:default/e03e7e542e356d18f90440a4a5d6261e1972d346
  - Component:default/f201386beb45b093937fc803ce53dd905b0bd971
  - Component:default/8aca16a253beb3ea1c235ee105e49a9923d000b9
  - Component:default/a35d8347890c829b7e9530c6f84e29db57690d3c
  - Component:default/e6eaae2b3b3cf67c7bf13e48dc79fff348a00344
  - Component:default/05dfbb2469a77dce42ea1452fd85d8f060f12701
  - Component:default/53344371e58b2b00b8d146711821f13595cab6c4
  - Component:default/7489214fe02ba6ba64c1250d4c14e3340bbd7f0b
  - Component:default/1af346b2f1c50b749048b3093f2f5797ea9baa8d
  - Component:default/e1d2a0c945b35720247c5da666751df1390354a1
  - Component:default/05aa47bf5c76c26a7d277f9f9ec4a08100de1b6a
  - Component:default/2035e5979be5cac41e64da612ea10461f7916026
  - Component:default/19e742349865f76734857900e11d2cdc51c66228
  - Component:default/a4d6531c838310c9caa7ab618de18c9aa930a7c8
  - Component:default/841c6e9211e7e907e33db5201eafbf9a47599a3e
  - Component:default/9a665758631319f1c4b1ded550386a68f62cf623
  - Component:default/d553d32172cb31613edf2e8544245fd20a7217c0
  - Component:default/1e9229ec940eae00119924e8a311508d8d2061c6
  - Component:default/4d9a0f0043a8e565367ac33fe06348b4be2e013c
  - Component:default/753fae129437d0c3ec6183d9ac66b57623789549
  - Component:default/3fb0cf6850c8aa1624e42c1d6372d5d747dcee42
  - Component:default/d8730214077ebaad7216c490b4d2fcc4fda3ef7d
  - Component:default/4a49c3bd15fe682f13b8bd190d546d993e43d858
  - Component:default/9e56163af492aeecf37a8d5c592a51de18f94fb4
  - Component:default/44483eaa61bc0f090b4e62ad0ea20fd14282e80e
  - Component:default/7e1be8946894b6ca93a7c18953f5d76a259243cd
  - Component:default/c3a5f34c21e76e37f3e3ce0e857f5f2e971de9a1
  - Component:default/639f22d35c5f8366b935859ecfe2ed282a3912aa
  - Component:default/4cbaa65d960c400c9b98f822ccc767f5a0e0bd31
  - Component:default/91c4113a7e8dfc7b7eebbc3d0cd5eecf0df170c6
  - Component:default/8089de52a3caa9ab4aa744f50f4264ca5ff9becd
  - Component:default/c60f1126e0c99535373a755f2a71082863cd0ae4
  - Component:default/b6be0e3ec710848c729734ec71a55355ca2e50fa
  - Component:default/69008417a9ca3897676992b312be3dc866b3df85
  - Component:default/bd4817e3af1e8e1e175aa7270745d022da731f47
  - Component:default/a5d9340911e7e6a61c6e70ed22e855b28d21ac77
  - Component:default/454e724a454306b909f1db2b8994c8a197f11011
  - Component:default/fd798c5dfd65c7bb38334f45c312f58d3073ea53
  - Component:default/ba50f85d50670337ecf011b6276e2a6f3395b5c2
  - Component:default/823eefb81f1613f6c8550d66b3174633f6ba7cc4
  - Component:default/7bd65eb3ed83e0607ff6d945e35cb687dbf11a85
  - Component:default/ca31dd891d416bc3f4e68ba5edcf1e9399e93b6d
  - Component:default/2b640cb647696ea72f503252bee78419180f7428
  - Component:default/da1e754de291eb2eaac2420349485cc494e0556d
