apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 91f5b78f48fdcea8a1e82787a217df1b8089e751
  description: ""
  annotations:
    pkg/source: github.com/pkman92/package-analyzer
    pkg/version: 0.0.0
spec:
  type: library
  lifecycle: experimental
  system: gomodules
  owner: gomodules
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e028427f92590f74d449f768ce57b2f6be23e4ae
  description: ""
  annotations:
    pkg/source: gopkg.in/check.v1
    pkg/version: v0.0.0-20161208181325-20d25e280405
spec:
  type: library
  lifecycle: experimental
  system: gomodules
  owner: gomodules
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 17eb86a1a117eb0fbb4eb9947663904d836f33f5
  description: ""
  annotations:
    pkg/source: gopkg.in/yaml.v2
    pkg/version: v2.4.0
spec:
  type: library
  lifecycle: experimental
  system: gomodules
  owner: gomodules
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c47645c391ad0571c40779079363c9d48412e18b
  description: ""
  annotations:
    pkg/base_image: ""
    pkg/browse_url: https://app.snyk.io/org/pkman92/project/815c6687-add8-44f8-9861-fedfb2ae8b41
    pkg/image_tag: 0.0.0
    pkg/repo: pkman92/package-analyzer
    pkg/source: go.mod
    pkg/vulnerabilities: '{"low":0,"medium":0,"high":0,"critical":0}'
spec:
  type: service
  lifecycle: experimental
  system: domain-1
  owner: gomodules
  dependsOn:
  - Component:default/91f5b78f48fdcea8a1e82787a217df1b8089e751
  - Component:default/e028427f92590f74d449f768ce57b2f6be23e4ae
  - Component:default/17eb86a1a117eb0fbb4eb9947663904d836f33f5
