apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 52edd1dffabcf1f1dc0e57ff34f88738137e6be4
  description: ""
  annotations:
    pkg/source: '@backstage/search-common'
    pkg/version: 0.2.2
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: be03af19c39444e540e49d15a2b85299c621d779
  description: ""
  annotations:
    pkg/source: '@backstage/plugin-permission-common'
    pkg/version: ^0.4.0-next.0
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4f4f8b2b6aabb90ee254954db7029aee645a933f
  description: ""
  annotations:
    pkg/source: '@backstage/types'
    pkg/version: ^0.1.1
spec:
  type: library
  lifecycle: experimental
  system: yarn
  owner: yarn
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 18af7923f87bc56d99fc3103e977e72e6fc21336
  description: ""
  annotations:
    pkg/base_image: ""
    pkg/browse_url: https://app.snyk.io/org/pkman92/project/93ff6dbf-986e-4764-836e-eb11f0bbccd0
    pkg/image_tag: 0.2.2
    pkg/repo: pkman92/backstage
    pkg/source: packages/search-common/package.json
    pkg/vulnerabilities: '{"low":0,"medium":0,"high":0,"critical":0}'
spec:
  type: service
  lifecycle: experimental
  system: domain-1
  owner: yarn
  dependsOn:
  - Component:default/52edd1dffabcf1f1dc0e57ff34f88738137e6be4
  - Component:default/be03af19c39444e540e49d15a2b85299c621d779
  - Component:default/4f4f8b2b6aabb90ee254954db7029aee645a933f
