apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 24c481343c720183aff9a159e9a747a76db341de
  description: ""
  annotations:
    pkg/source: cloud.google.com/go
    pkg/version: v0.34.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e75c439234a9d07031151cb359bedecb9079884d
  description: ""
  annotations:
    pkg/source: github.com/BurntSushi/toml
    pkg/version: v0.3.1
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a34ec874511114bc335c9ba4e2b276e7b156cd1f
  description: ""
  annotations:
    pkg/source: github.com/OneOfOne/xxhash
    pkg/version: v1.2.2
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4969757ecdbfe0f3a3710551d737c9fe7c003fe1
  description: ""
  annotations:
    pkg/source: github.com/antihax/optional
    pkg/version: v1.0.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e434fb9f6174a34c85caa2bfcef559854a0c9545
  description: ""
  annotations:
    pkg/source: github.com/census-instrumentation/opencensus-proto
    pkg/version: v0.2.1
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: f012b373f3ffaafc193d66dadd26df1c30b368ae
  description: ""
  annotations:
    pkg/source: github.com/cespare/xxhash
    pkg/version: v1.1.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4284dd833f9b9cdf7646eefbb300957d4b913844
  description: ""
  annotations:
    pkg/source: github.com/client9/misspell
    pkg/version: v0.3.4
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 375a3f4c4b8ada360cde96c2dfc5eb10f5c413a0
  description: ""
  annotations:
    pkg/source: github.com/cncf/udpa/go
    pkg/version: v0.0.0-20201120205902-5459f2c99403
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 3d6f65aeb20972d60c8d0c770a9059f798c8dfe7
  description: ""
  annotations:
    pkg/source: github.com/cncf/xds/go
    pkg/version: v0.0.0-20210312221358-fbca930ec8ed
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 18406cf5ea3d310ada656c952f498b44fa35cbd8
  description: ""
  annotations:
    pkg/source: github.com/creack/pty
    pkg/version: v1.1.9
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a3fe0798cbdcc9ecdb16165fc52921491e64b4f7
  description: ""
  annotations:
    pkg/source: github.com/davecgh/go-spew
    pkg/version: v1.1.1
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 54793d4f71e627d054426ba849080ed7e0f42d51
  description: ""
  annotations:
    pkg/source: github.com/envoyproxy/go-control-plane
    pkg/version: v0.9.9-0.20210512163311-63b5d3c536b0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: baefe43c5497b563d3abbf8ef2e60e7fc08ffe25
  description: ""
  annotations:
    pkg/source: github.com/envoyproxy/protoc-gen-validate
    pkg/version: v0.1.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8ab806a9dae95c02011cf84bb3bdccd229ca21e1
  description: ""
  annotations:
    pkg/source: github.com/ghodss/yaml
    pkg/version: v1.0.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 0c2e6f3ec8d0ff3d08659aa6956849927282ed01
  description: ""
  annotations:
    pkg/source: github.com/gogo/protobuf
    pkg/version: v1.3.2
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 51120b7047877391dcd1fad30179c42d1c28b610
  description: ""
  annotations:
    pkg/source: github.com/golang/glog
    pkg/version: v0.0.0-20160126235308-23def4e6c14b
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 23f7bf22679de0bef28f262718efc12226d322fe
  description: ""
  annotations:
    pkg/source: github.com/golang/mock
    pkg/version: v1.1.1
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 12a279cbf1e82f585a6d7b5bc20932e6d015533b
  description: ""
  annotations:
    pkg/source: github.com/golang/protobuf
    pkg/version: v1.5.2
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 79a818d9ee43d68c2ca1928e6d8e8d56d19afcc5
  description: ""
  annotations:
    pkg/source: github.com/google/go-cmp
    pkg/version: v0.5.5
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9497d03fcb444ab217f6af9a10a92987e25f218a
  description: ""
  annotations:
    pkg/source: github.com/google/uuid
    pkg/version: v1.1.2
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 1fef74196b9ba20e2a2c000a6640a9877f22df8f
  description: ""
  annotations:
    pkg/source: github.com/grpc-ecosystem/grpc-gateway
    pkg/version: v1.16.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 518945e4aca9dd1553f7837d7875cb162c787c8c
  description: ""
  annotations:
    pkg/source: github.com/kisielk/errcheck
    pkg/version: v1.5.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 1da5d1bed32f9facc60d0badf602315663b9d1e6
  description: ""
  annotations:
    pkg/source: github.com/kisielk/gotool
    pkg/version: v1.0.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dce76e9f41832f2d643f4765c4a0d0460decb34d
  description: ""
  annotations:
    pkg/source: github.com/kr/pty
    pkg/version: v1.1.1
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 73c8b34f7a0cb97d11b35d02a9f0fb1ab831bdad
  description: ""
  annotations:
    pkg/source: github.com/kr/text
    pkg/version: v0.2.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e4f8d6af9737a461b459977ca0187aab69590ba9
  description: ""
  annotations:
    pkg/source: github.com/niemeyer/pretty
    pkg/version: v0.0.0-20200227124842-a10e7caefd8e
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cbda1b99c2528ac01d27623befa9e00cb4d6c5ca
  description: ""
  annotations:
    pkg/source: github.com/pmezard/go-difflib
    pkg/version: v1.0.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 61830a678ec431e8e8037b8ef5ea5f2a11174aa7
  description: ""
  annotations:
    pkg/source: github.com/prometheus/client_model
    pkg/version: v0.0.0-20190812154241-14fe0d1b01d4
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a488c7cd785fd6cb4b59f424f5a500ea01a65722
  description: ""
  annotations:
    pkg/source: github.com/rogpeppe/fastuuid
    pkg/version: v1.2.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: b756fdc151981fcd0ae800def74676a8874c6e56
  description: ""
  annotations:
    pkg/source: github.com/spaolacci/murmur3
    pkg/version: v0.0.0-20180118202830-f09979ecbc72
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a5e8d11460d7b416769adcbb25d7673ed6f0a3a4
  description: ""
  annotations:
    pkg/source: github.com/stretchr/objx
    pkg/version: v0.1.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a1aaeeec968b82e8beeeb67c1236709bbcefce9d
  description: ""
  annotations:
    pkg/source: github.com/stretchr/testify
    pkg/version: v1.7.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fbe05ad2075391ed1942b9d541a2617675d9aca5
  description: ""
  annotations:
    pkg/source: github.com/yuin/goldmark
    pkg/version: v1.3.5
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 0328eb1248bd63476d55588493eb5620ec4ac632
  description: ""
  annotations:
    pkg/source: go.opentelemetry.io/proto/otlp
    pkg/version: v0.7.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 506a05ddaa7445fcd4fcd58b3094f85e6ce91067
  description: ""
  annotations:
    pkg/source: golang.org/x/crypto
    pkg/version: v0.0.0-20200622213623-75b288015ac9
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: f896bf22bcd4ceb56241e7482ad8df51a2de80e6
  description: ""
  annotations:
    pkg/source: golang.org/x/exp
    pkg/version: v0.0.0-20190121172915-509febef88a4
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ada340668439fc61270c664563ff12213cf7073c
  description: ""
  annotations:
    pkg/source: golang.org/x/lint
    pkg/version: v0.0.0-20210508222113-6edffad5e616
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 76b1de679e11013bda983cc03903f5ca2d7ac0d1
  description: ""
  annotations:
    pkg/source: golang.org/x/mod
    pkg/version: v0.4.2
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 53dcdb0f22947e7121b57cfddd80e714674ef385
  description: ""
  annotations:
    pkg/source: golang.org/x/net
    pkg/version: v0.0.0-20211209124913-491a49abca63
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 3c8d682744aa10f73c3111ce68e09da5285bff3d
  description: ""
  annotations:
    pkg/source: golang.org/x/oauth2
    pkg/version: v0.0.0-20200107190931-bf48bf16ab8d
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: d98285acf7c9f71e4ca0ee382461079ab78a2599
  description: ""
  annotations:
    pkg/source: golang.org/x/sync
    pkg/version: v0.0.0-20210220032951-036812b2e83c
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 1f39b1e492a4c18884e75910ae82aa8cf5063231
  description: ""
  annotations:
    pkg/source: golang.org/x/sys
    pkg/version: v0.0.0-20220114195835-da31bd327af9
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: f97a721cef6d50d741dc77e8b5785f025db6d2d2
  description: ""
  annotations:
    pkg/source: golang.org/x/term
    pkg/version: v0.0.0-20201126162022-7de9c90e9dd1
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c7fbef80b085725e5312e516192ec8ca61fb30e8
  description: ""
  annotations:
    pkg/source: golang.org/x/text
    pkg/version: v0.3.7
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ed2a2bcbce1d30ff6bcb74c05076695159edb1af
  description: ""
  annotations:
    pkg/source: golang.org/x/tools
    pkg/version: v0.1.5
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9ac6259e74c39d883584c9ebca0d69cb8e6e25f7
  description: ""
  annotations:
    pkg/source: golang.org/x/xerrors
    pkg/version: v0.0.0-20200804184101-5ec99f83aff1
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: f3571ce1fa98c2e5923a434add37c34167531660
  description: ""
  annotations:
    pkg/source: google.golang.org/appengine
    pkg/version: v1.4.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 6e30fc73bb85a60d3405e4822e3d63d3a9c95bc0
  description: ""
  annotations:
    pkg/source: google.golang.org/genproto
    pkg/version: v0.0.0-20210831024726-fe130286e0e2
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 86d38d9b204b74b927cecde2cccaeb16779e14ce
  description: ""
  annotations:
    pkg/source: google.golang.org/grpc
    pkg/version: v1.40.0
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: d9623ced8ca3b536e4073f9d0eb5d94c8c8bb0bc
  description: ""
  annotations:
    pkg/source: google.golang.org/protobuf
    pkg/version: v1.27.1
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 0cba460b19916098397277e197afb7501c51836a
  description: ""
  annotations:
    pkg/source: gopkg.in/check.v1
    pkg/version: v1.0.0-20200227125254-8fa46927fb4f
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 5e8ee2dffe85671640686cfa81541346bb521c25
  description: ""
  annotations:
    pkg/source: gopkg.in/yaml.v2
    pkg/version: v2.2.3
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 3d28fd7447d31638a595a2e2e18a54f4eff490fe
  description: ""
  annotations:
    pkg/source: gopkg.in/yaml.v3
    pkg/version: v3.0.0-20210107192922-496545a6307b
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 6d92334f8b6e1d4f99365137607b94dc8ecf60aa
  description: ""
  annotations:
    pkg/source: honnef.co/go/tools
    pkg/version: v0.0.0-20190523083050-ea95bdfd59fc
spec:
  type: library
  lifecycle: experimental
  system: go-modules
  owner: go
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: be50a11499ae046e8ecd55782201894cd0829752
  description: ""
  annotations:
    pkg/source: k8s.io/cri-api
spec:
  type: service
  lifecycle: experimental
  system: domain-1
  owner: go
  dependsOn:
  - Component:default/24c481343c720183aff9a159e9a747a76db341de
  - Component:default/e75c439234a9d07031151cb359bedecb9079884d
  - Component:default/a34ec874511114bc335c9ba4e2b276e7b156cd1f
  - Component:default/4969757ecdbfe0f3a3710551d737c9fe7c003fe1
  - Component:default/e434fb9f6174a34c85caa2bfcef559854a0c9545
  - Component:default/f012b373f3ffaafc193d66dadd26df1c30b368ae
  - Component:default/4284dd833f9b9cdf7646eefbb300957d4b913844
  - Component:default/375a3f4c4b8ada360cde96c2dfc5eb10f5c413a0
  - Component:default/3d6f65aeb20972d60c8d0c770a9059f798c8dfe7
  - Component:default/18406cf5ea3d310ada656c952f498b44fa35cbd8
  - Component:default/a3fe0798cbdcc9ecdb16165fc52921491e64b4f7
  - Component:default/54793d4f71e627d054426ba849080ed7e0f42d51
  - Component:default/baefe43c5497b563d3abbf8ef2e60e7fc08ffe25
  - Component:default/8ab806a9dae95c02011cf84bb3bdccd229ca21e1
  - Component:default/0c2e6f3ec8d0ff3d08659aa6956849927282ed01
  - Component:default/51120b7047877391dcd1fad30179c42d1c28b610
  - Component:default/23f7bf22679de0bef28f262718efc12226d322fe
  - Component:default/12a279cbf1e82f585a6d7b5bc20932e6d015533b
  - Component:default/79a818d9ee43d68c2ca1928e6d8e8d56d19afcc5
  - Component:default/9497d03fcb444ab217f6af9a10a92987e25f218a
  - Component:default/1fef74196b9ba20e2a2c000a6640a9877f22df8f
  - Component:default/518945e4aca9dd1553f7837d7875cb162c787c8c
  - Component:default/1da5d1bed32f9facc60d0badf602315663b9d1e6
  - Component:default/dce76e9f41832f2d643f4765c4a0d0460decb34d
  - Component:default/73c8b34f7a0cb97d11b35d02a9f0fb1ab831bdad
  - Component:default/e4f8d6af9737a461b459977ca0187aab69590ba9
  - Component:default/cbda1b99c2528ac01d27623befa9e00cb4d6c5ca
  - Component:default/61830a678ec431e8e8037b8ef5ea5f2a11174aa7
  - Component:default/a488c7cd785fd6cb4b59f424f5a500ea01a65722
  - Component:default/b756fdc151981fcd0ae800def74676a8874c6e56
  - Component:default/a5e8d11460d7b416769adcbb25d7673ed6f0a3a4
  - Component:default/a1aaeeec968b82e8beeeb67c1236709bbcefce9d
  - Component:default/fbe05ad2075391ed1942b9d541a2617675d9aca5
  - Component:default/0328eb1248bd63476d55588493eb5620ec4ac632
  - Component:default/506a05ddaa7445fcd4fcd58b3094f85e6ce91067
  - Component:default/f896bf22bcd4ceb56241e7482ad8df51a2de80e6
  - Component:default/ada340668439fc61270c664563ff12213cf7073c
  - Component:default/76b1de679e11013bda983cc03903f5ca2d7ac0d1
  - Component:default/53dcdb0f22947e7121b57cfddd80e714674ef385
  - Component:default/3c8d682744aa10f73c3111ce68e09da5285bff3d
  - Component:default/d98285acf7c9f71e4ca0ee382461079ab78a2599
  - Component:default/1f39b1e492a4c18884e75910ae82aa8cf5063231
  - Component:default/f97a721cef6d50d741dc77e8b5785f025db6d2d2
  - Component:default/c7fbef80b085725e5312e516192ec8ca61fb30e8
  - Component:default/ed2a2bcbce1d30ff6bcb74c05076695159edb1af
  - Component:default/9ac6259e74c39d883584c9ebca0d69cb8e6e25f7
  - Component:default/f3571ce1fa98c2e5923a434add37c34167531660
  - Component:default/6e30fc73bb85a60d3405e4822e3d63d3a9c95bc0
  - Component:default/86d38d9b204b74b927cecde2cccaeb16779e14ce
  - Component:default/d9623ced8ca3b536e4073f9d0eb5d94c8c8bb0bc
  - Component:default/0cba460b19916098397277e197afb7501c51836a
  - Component:default/5e8ee2dffe85671640686cfa81541346bb521c25
  - Component:default/3d28fd7447d31638a595a2e2e18a54f4eff490fe
  - Component:default/6d92334f8b6e1d4f99365137607b94dc8ecf60aa
