apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 31b70a8ed239cf9ec698bb84a18ff8e69c8a1760
  description: ""
  annotations:
    pkg/source: node
    pkg/version: 14-alpine
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8829c1f448fc74abec716b8116d6ea66fb5b0401
  description: ""
  annotations:
    pkg/source: alpine-baselayout/alpine-baselayout
    pkg/version: 3.2.0-r18
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ca2216d3d130a7a7a4112ac3fc0c9cf0ad886a67
  description: ""
  annotations:
    pkg/source: alpine-keys/alpine-keys
    pkg/version: 2.4-r1
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: e2c330f240e8789dcb167e4a3dbde537e5cb50e3
  description: ""
  annotations:
    pkg/source: apk-tools/apk-tools
    pkg/version: 2.12.7-r3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8c2e6e456d6c9d138d4488f63a5d61d17a5dd75b
  description: ""
  annotations:
    pkg/source: busybox/busybox
    pkg/version: 1.34.1-r3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: c6c3eedcb81c89892fd42c4b6acf409e7596b491
  description: ""
  annotations:
    pkg/source: busybox/ssl_client
    pkg/version: 1.34.1-r3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 41005ff7922c6f9e912674eee9eedbc6f7c12753
  description: ""
  annotations:
    pkg/source: ca-certificates/ca-certificates-bundle
    pkg/version: 20191127-r7
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 6cf511d96029f750f9cf2f2ce64d5c33bbe4c7e5
  description: ""
  annotations:
    pkg/source: gcc/libgcc
    pkg/version: 10.3.1_git20211027-r0
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 16130956bbee3efe8c40d5411d8d868b41fb9736
  description: ""
  annotations:
    pkg/source: gcc/libstdc++
    pkg/version: 10.3.1_git20211027-r0
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 8d01d0131fec5ac4e6d3f1230fbe107cb72110e7
  description: ""
  annotations:
    pkg/source: libc-dev/libc-utils
    pkg/version: 0.7.2-r3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acbbdf90810e48cd9b6e71e08bd9291eabb0cb6d
  description: ""
  annotations:
    pkg/source: libretls/libretls
    pkg/version: 3.3.4-r2
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 90780f2137888de987e25c75542bbbb2654d1853
  description: ""
  annotations:
    pkg/source: musl/musl
    pkg/version: 1.2.2-r7
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 603c453af1cb0ddadc584a741b92d5e476958137
  description: ""
  annotations:
    pkg/source: musl/musl-utils
    pkg/version: 1.2.2-r7
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a64d9559c3bfd7ef80a612466f6c2332a75bda8a
  description: ""
  annotations:
    pkg/source: openssl/libcrypto1.1
    pkg/version: 1.1.1l-r7
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 0dedffcbb85460ec6b35889d0efb6502cce2abb7
  description: ""
  annotations:
    pkg/source: openssl/libssl1.1
    pkg/version: 1.1.1l-r7
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 20815b04fd27b64c7beaecf68a07c72aef022343
  description: ""
  annotations:
    pkg/source: pax-utils/scanelf
    pkg/version: 1.3.3-r0
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 9059a21aed5915f37a64e1fdd3880662603bfb05
  description: ""
  annotations:
    pkg/source: zlib/zlib
    pkg/version: 1.2.11-r3
spec:
  type: library
  lifecycle: experimental
  system: dockerfile
  owner: dockerfile
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 81b61693241747022d22a2a2599d47153f16b5a0
  description: ""
  annotations:
    pkg/base_image: node:14-alpine
    pkg/browse_url: https://app.snyk.io/org/pkman92/project/4dce960c-6c82-44bc-b697-233af78de72a
    pkg/image_tag: 14-alpine
    pkg/repo: pkman92/backstage
    pkg/source: contrib/docker/devops/Dockerfile
    pkg/vulnerabilities: '{"low":0,"medium":0,"high":0,"critical":0}'
spec:
  type: service
  lifecycle: experimental
  system: domain-1
  owner: dockerfile
  dependsOn:
  - Component:default/31b70a8ed239cf9ec698bb84a18ff8e69c8a1760
  - Component:default/8829c1f448fc74abec716b8116d6ea66fb5b0401
  - Component:default/ca2216d3d130a7a7a4112ac3fc0c9cf0ad886a67
  - Component:default/e2c330f240e8789dcb167e4a3dbde537e5cb50e3
  - Component:default/8c2e6e456d6c9d138d4488f63a5d61d17a5dd75b
  - Component:default/c6c3eedcb81c89892fd42c4b6acf409e7596b491
  - Component:default/41005ff7922c6f9e912674eee9eedbc6f7c12753
  - Component:default/6cf511d96029f750f9cf2f2ce64d5c33bbe4c7e5
  - Component:default/16130956bbee3efe8c40d5411d8d868b41fb9736
  - Component:default/8d01d0131fec5ac4e6d3f1230fbe107cb72110e7
  - Component:default/acbbdf90810e48cd9b6e71e08bd9291eabb0cb6d
  - Component:default/90780f2137888de987e25c75542bbbb2654d1853
  - Component:default/603c453af1cb0ddadc584a741b92d5e476958137
  - Component:default/a64d9559c3bfd7ef80a612466f6c2332a75bda8a
  - Component:default/0dedffcbb85460ec6b35889d0efb6502cce2abb7
  - Component:default/20815b04fd27b64c7beaecf68a07c72aef022343
  - Component:default/9059a21aed5915f37a64e1fdd3880662603bfb05
